#!/bin/bash -eu

set -o pipefail

readonly VERSION=${1:-$(date +%Y.%M.%-d.0)}


cd "$(git rev-parse --show-toplevel)"

ydl_version=$(echo $(LANG=C pacman -Qi youtube-dl | grep ^Version | cut -d ':' -f 2 | cut -d '-' -f 1))
grep -v youtube-dl requirements.txt > requirements.txt.tmp
echo "youtube-dl>=$ydl_version" >> requirements.txt.tmp
sort -u -o requirements.txt.tmp requirements.txt.tmp
mv requirements.txt{.tmp,}
git add requirements.txt

sed -i "s/^\(__version__ = \"\).*\(\"\)/\1$VERSION\2/w /dev/stdout" amg/__init__.py
git add amg/__init__.py

git commit -m "Version ${VERSION}"

git tag -m "Version ${VERSION}" ${VERSION}
