#!/bin/bash -eux

set -o pipefail

readonly FFMPEG_VERSION=${1:?}
readonly PROC_COUNT=$([ $(which getconf) ] && getconf _NPROCESSORS_ONLN || grep -cE '^processor' /proc/cpuinfo)


configure() {
  ./configure --enable-gpl \
              --enable-version3 \
              --enable-nonfree \
              --disable-ffserver \
              --disable-debug
}

# dependencies
apt-get -y install yasm

# clone
repo_dir=$HOME/FFmpeg/$FFMPEG_VERSION
if [ "$FFMPEG_VERSION" = "master" ]
then
  branch_name=master
else
  branch_name=release/$FFMPEG_VERSION
fi
if [ -d $repo_dir ]
then
  # repo dir already exists
  cd $repo_dir
  if [ "$(git rev-parse @)" = "$(git rev-parse origin/$branch_name)" ]
  then
    # update
    git pull

    # cleanup
    make clean
    make distclean

    # (re)configure
    configure
  fi
else
  # clone & set branch
  git clone https://git.ffmpeg.org/ffmpeg.git $repo_dir
  cd $repo_dir
  git checkout $branch_name

  # configure
  configure
fi

# build
make -j $PROC_COUNT
make install

# update shared libs cache
ldconfig
