on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: astral-sh/setup-uv@v7
      - uses: j178/prek-action@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
        ffmpeg-version: ["", "7.0", "7.1", "8.0", "master"]

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@v5
        with:
          path: ~/.cache/ci/amg-player/ffmpeg
          key: ${{runner.os}}-ffmpeg-${{hashFiles('ci/install-ffmpeg')}}-${{matrix.ffmpeg-version}}
      - uses: actions/cache@v5
        with:
          path: ~/.cache/ci/amg-player/test
          key: testfiles-${{hashFiles('tests/test_tag.py')}}
      - if: ${{matrix.ffmpeg-version}}
        run: |
          sudo apt-get install yasm nasm
          ./ci/install-ffmpeg ${{matrix.ffmpeg-version}}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: uv sync
      - run: TEST_DL_CACHE_DIR=$HOME/.cache/ci/amg-player/test uv run python -m unittest discover -v .
