on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
      - uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14"]
        ffmpeg-version: ["", "8.1", "master"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: ${{matrix.python-version}}
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/ci/amg-player/ffmpeg
          key: ${{runner.os}}-ffmpeg-${{hashFiles('ci/install-ffmpeg')}}-${{matrix.ffmpeg-version}}
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/ci/amg-player/test
          key: testfiles-${{hashFiles('tests/test_tag.py')}}
      - if: ${{matrix.ffmpeg-version}}
        run: |
          sudo apt-get install yasm nasm
          ./ci/install-ffmpeg ${{matrix.ffmpeg-version}}
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: uv sync
      - run: TEST_DL_CACHE_DIR=$HOME/.cache/ci/amg-player/test uv run python -m unittest discover -v .
